    name: GitHub Classroom Workflow
    on: 
       push:
          paths: 
             - 'src/Exercise.hs'

    jobs:
       runhaskell:
           name: autograding
           runs-on: ubuntu-latest # or macOS-latest, or windows-latest
           steps:
             - uses: actions/checkout@v2
             - uses: haskell/actions/setup@v1
               with:
                  ghc-version: 'latest' # Exact version of ghc to use
                  # cabal-version: 'latest'. Omitted, but defaults to 'latest'
                  enable-stack: true
                  stack-version: 'latest'
             - run: stack test 
